# For deployment

version: '3'

services:

  flask_server:
    container_name: flask_server
    restart: always
    build: .
    volumes:
      - .:/app/i-care
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_server
